app-template:
  configMaps:
    config:
      data:
        openclaw.json: |
          {
            "browser": {
              "enabled": true,
              "defaultProfile": "openclaw",
              "profiles": {
                "openclaw": {
                  "cdpUrl": "http://localhost:9222"
                }
              }
            }
          }

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: librechat.cluster.dphx.eu
          paths:
            - path: /
              pathType: Prefix
              service:
                name: librechat
                port: 3080
      tls:
        - hosts:
            - librechat.cluster.dphx.eu
          secretName: librechat-tls
